DELETE  http://localhost:3001/api/persons/5f835e7186db4a1d461386cf

###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/5f835e7186db4a1d461386cf

###

POST    http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Lionel Messi",
    "number": "11-99980978"
}

###

PUT http://localhost:3001/api/persons/5f835e7186db4a1d461386cf
Content-Type: application/json

{
    "name": "Lionel Messii",
    "number": "11-99980978"
}


###

GET http://localhost:3001/info
